#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

# Add location of autostart file to path
BASE="$(dirname $0)"

hc lock
hc emit_hook reload

#feh -z --bg-fill ~/Dropbox/pictures/wallpapers/* ~/Dropbox/Apps/Desktoppr/*

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1
hc keybind $Mod-Shift-Escape quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Enter spawn urxvt
hc keybind $Mod-space spawn dmenu_run
hc keybind $Mod-Escape spawn ${HOME}/bin/lock
hc keybind $Mod-Alt-Escape spawn sudo /usr/sbin/pm-suspend
hc keybind $Mod-n spawn "${BASE}/renametag.sh"
# Volume bindings
# Smallest possible increment for volume
hc keybind $Mod-Alt-j spawn amixer set Master,0 1%-
hc keybind $Mod-Alt-k spawn amixer set Master,0 1%+
hc keybind $Mod-Alt-l spawn amixer set Master,0 toggle

# tags
TAG_NAMES=( {1..9} 0 )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    key="${TAG_KEYS[$i]}"
    name="${TAG_NAMES[$i]}"
    hc add $name
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma  use_index -1
hc keybind $Mod-Right  juse_index +1
hc keybind $Mod-Left   juse_index -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Tab cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind Alt-Tab          cycle_all +1
hc keybind Alt-Shift-Tab    cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc set focus_follows_mouse 1

# colors
color_active='#268bd2'
color_inactive='#93a1a1'
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 0
hc set window_border_width 2
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#268bd2'
hc set always_show_frame 1
hc set window_gap 3
hc set frame_bg_transparent 1

# rules
hc unrule -F
hc rule focus=on # Normally focus new windows.
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# Set up multi monitors
while [[ $(hc list_monitors | wc -l) -gt 1 ]]; do
    hc remove_monitor 1
done

# tags
NUM_MONS=$(xrandr --current | grep "^\w.* connected" | wc -l)
MON_RES=( $(xrandr --current | grep "^\w.* connected" | awk '{print $3}') )
MON_NUMS=$( python -c "for i in range(${NUM_MONS}): print(i)" )

for i in ${MON_NUMS[@]} ; do
    echo "${i}"
    if [[ $i == '0' ]]; then
        hc move_monitor $i ${MON_RES[$i]};
    else
        hc add_monitor ${MON_RES[$i]};
    fi
done

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

# unlock, just to be sure
hc unlock
